export const List = [
        {
                id: 1001, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1002, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1003, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1004, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1005, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1006, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1007, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1008, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1009, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1010, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1011, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1012, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1013, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1014, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1015, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1016, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1017, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1018, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1019, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1020, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1021, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1022, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1023, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1029, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1030, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1031, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1032, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1033, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1034, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1035, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1036, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1037, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1038, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1039, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1040, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1040, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1042, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1043, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1044, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1045, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1046, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1048, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1049, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        {
                id: 1050, 
                city: 'delhi',
                img: 'https://r1imghtlak.mmtcdn.com/082f1ae6330211eb9c050242ac110004.jpg?&output-quality=75&downsize=583:388&output-format=jpg',
                hotelName: 'Hotel Tower Street',
                distance: '3km from airport',
                free: 'Free WiFi | Free airport taxi',
                roomType: 'Deluxe | Super Deluxe',
                roomDetail: 'Entire studio | 1 Bathroom | 700 square feet | 1 Bedroom',
                rating: 4.8,
                price: 799,
                couple: 'Couple Friendly'
        },
        
]